user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user


common:
    resource: "@CommonBundle/Resources/config/routing.xml"
    prefix:   /home

app:
    resource: '@AppBundle/Controller/'
    type: annotation