<?php

namespace UserManagement\UserBundle\Repository;

/**
 * RewardCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
